[package]
name = "wasm_bindgen_helper"
description = "wasm bindgen helpers"
edition = "2021"
license = "LicenseRef-DCL-1.0"
version = "0.0.0"
homepage = "https://github.com/rainprotocol/rain.wasm"

[dependencies]
alloy = "0.1.4"
paste = { version = "1.0.15" }
js-sys = { version = "0.3.77" }
wasm-bindgen = { version = "0.2.100" }
serde-wasm-bindgen = { version = "0.6.5" }
wasm-bindgen-futures = { version = "0.4.50" }
serde = { version = "1.0.217", features = ["derive", "rc"] }
tsify = { version = "0.4.5", default-features = false, features = ["js", "wasm-bindgen"] }

[dev-dependencies]
serde_test = "1.0.177"
wasm-bindgen-test = "0.3.50"
