name: Release
on:
  workflow_dispatch:
    inputs:
      version-level:
        description: 'Select Version Level'
        required: true
        type: choice
        options:
          - alpha   # Increase the alpha pre-version (x.y.z-alpha.M)
          - beta    # Increase the beta pre-version (x.y.z-beta.M)
          - patch   # Increase the patch version (x.y.z)
          - minor   # Increase the minor version (x.y.0)
          - major   # Increase the major version (x.0.0)
          - release # Remove the pre-version, ie remove alpha/beta/rc (x.y.z)
          - rc      # Increase the rc pre-version (x.y.z-rc.M)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.PUBLISHER_SSH_KEY }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main

      - run: nix develop -c rainix-rs-artifacts
      - run: nix develop -c rainix-rs-test
      - run: nix develop -c rainix-rs-static
      - run: nix develop -c rainix-wasm-artifacts
      - run: nix develop -c rainix-wasm-test

      - name: Git Config
        run: |
          git config --global user.email "${{ secrets.CI_GIT_EMAIL }}"
          git config --global user.name "${{ secrets.CI_GIT_USER }}"

      - name: Publish to crates.io
        run: nix develop -c cargo release --no-confirm --execute --no-tag ${{ inputs.version-level }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Get Version
        run: echo "NEW_VERSION=v$(cargo pkgid | cut -d@ -f2 | cut -d' ' -f1)" >> $GITHUB_ENV

      # Commit changes and tag
      - name: Commit And Tag
        run: git tag ${{ env.NEW_VERSION }}

      # Push the commit to remote
      - name: Push Changes To Remote
        run: git push origin ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create gitHub release with npm tarball
      - name: Create GitHub Release
        id: gh_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
