name: Rainix CI
on: [push]

concurrency:
  group: ${{ github.ref }}-rainix
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  rainix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        task: [rainix-rs-test, rainix-rs-artifacts]
        include:
          # We don't need to do rust static analysis on multiple platforms
          - os: ubuntu-latest
            task: rainix-rs-static
            # Wasm target doesnt need to run on multiple platforms
          - os: ubuntu-latest
            task: rainix-wasm-artifacts
          - os: ubuntu-latest
            task: rainix-wasm-test
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix develop -c rainix-rs-prelude

      - name: Run ${{ matrix.task }}
        run: nix develop -c ${{ matrix.task }}
